/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ProyectoFinal;

import Clases.datosLogin;
import Lógica.componentes;
import javax.swing.JOptionPane;

/**
 *
 * @author Francisco
 */
public class Registro extends javax.swing.JFrame {

    /**
     * Creates new form Registro
     */
    public Registro() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        pnlPricipal = new javax.swing.JPanel();
        lblIconoUsername = new javax.swing.JLabel();
        lblIconoPassword = new javax.swing.JLabel();
        lblIconoEmail = new javax.swing.JLabel();
        lblIconoRegistro = new javax.swing.JLabel();
        txtpssContraseña = new javax.swing.JPasswordField();
        txtUserName = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        rsbtnRegistrase = new rsbuttom.RSButtonMetro();
        btnVolverLogin = new rsbuttom.RSButtonMetro();
        rbtnAdmin = new javax.swing.JRadioButton();
        rbtnVendedor = new javax.swing.JRadioButton();
        lblFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(416, 334, -1, -1));

        pnlPricipal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblIconoUsername.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/usuario.png"))); // NOI18N
        pnlPricipal.add(lblIconoUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 170, -1, 30));

        lblIconoPassword.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/candado.png"))); // NOI18N
        pnlPricipal.add(lblIconoPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 230, -1, 30));

        lblIconoEmail.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/Icono correo.png"))); // NOI18N
        pnlPricipal.add(lblIconoEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 290, -1, 30));

        lblIconoRegistro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/Icono de registro2.png"))); // NOI18N
        pnlPricipal.add(lblIconoRegistro, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 20, -1, -1));

        txtpssContraseña.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        pnlPricipal.add(txtpssContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(92, 230, 200, 30));

        txtUserName.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtUserName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUserNameActionPerformed(evt);
            }
        });
        pnlPricipal.add(txtUserName, new org.netbeans.lib.awtextra.AbsoluteConstraints(94, 170, 200, 30));

        txtEmail.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        pnlPricipal.add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(94, 290, 200, 30));

        rsbtnRegistrase.setBackground(new java.awt.Color(0, 0, 0));
        rsbtnRegistrase.setText("Registrarse");
        rsbtnRegistrase.setColorHover(new java.awt.Color(102, 0, 102));
        rsbtnRegistrase.setColorNormal(new java.awt.Color(0, 0, 0));
        rsbtnRegistrase.setColorTextHover(new java.awt.Color(102, 0, 102));
        rsbtnRegistrase.setColorTextPressed(new java.awt.Color(102, 0, 102));
        rsbtnRegistrase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rsbtnRegistraseActionPerformed(evt);
            }
        });
        pnlPricipal.add(rsbtnRegistrase, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 380, 160, 30));

        btnVolverLogin.setBackground(new java.awt.Color(0, 0, 0));
        btnVolverLogin.setText("Volver");
        btnVolverLogin.setColorHover(new java.awt.Color(153, 0, 153));
        btnVolverLogin.setColorNormal(new java.awt.Color(0, 0, 0));
        btnVolverLogin.setColorTextHover(new java.awt.Color(153, 0, 153));
        btnVolverLogin.setColorTextPressed(new java.awt.Color(153, 0, 153));
        btnVolverLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverLoginActionPerformed(evt);
            }
        });
        pnlPricipal.add(btnVolverLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 470, 80, -1));

        rbtnAdmin.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        rbtnAdmin.setText("Administrador");
        pnlPricipal.add(rbtnAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 340, -1, -1));

        rbtnVendedor.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        rbtnVendedor.setText("Vendedor");
        pnlPricipal.add(rbtnVendedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 340, 100, -1));

        lblFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/fondo login.png"))); // NOI18N
        pnlPricipal.add(lblFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 410, 510));

        getContentPane().add(pnlPricipal, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtUserNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUserNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUserNameActionPerformed

    private void rsbtnRegistraseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rsbtnRegistraseActionPerformed
        // Almacenamiento de usuarios
        String usuario = txtUserName.getText();
        String contraseña = String.valueOf(txtpssContraseña.getPassword());
        String email = txtEmail.getText();
        
        String rol = "";
        
        if (rbtnAdmin.isSelected()) {
            rol = "Administrador";
        }else if (rbtnVendedor.isSelected()) {
            rol = "Vendedor";
        }
        
        datosLogin D = new datosLogin();
        D.setUsuario(usuario);
        D.setContraseña(contraseña);
        D.setEmail(email);
        D.setRoles(rol);
        
        componentes.usuarios.add(D);
        
        JOptionPane.showMessageDialog(rootPane, "Usuario registrado: " + rol);
        
    }//GEN-LAST:event_rsbtnRegistraseActionPerformed

    private void btnVolverLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverLoginActionPerformed
        // Volver al login
        Login l = new Login();
        l.setVisible(true);
        
        dispose();
    }//GEN-LAST:event_btnVolverLoginActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Registro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private rsbuttom.RSButtonMetro btnVolverLogin;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblFondo;
    private javax.swing.JLabel lblIconoEmail;
    private javax.swing.JLabel lblIconoPassword;
    private javax.swing.JLabel lblIconoRegistro;
    private javax.swing.JLabel lblIconoUsername;
    private javax.swing.JPanel pnlPricipal;
    private javax.swing.JRadioButton rbtnAdmin;
    private javax.swing.JRadioButton rbtnVendedor;
    private rsbuttom.RSButtonMetro rsbtnRegistrase;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtUserName;
    private javax.swing.JPasswordField txtpssContraseña;
    // End of variables declaration//GEN-END:variables
}
